repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=88]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--ignore-missing-imports, --show-error-codes]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, security/configs/bandit.yml]
        exclude: ^tests/

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        args: [--write-changes]
        exclude: \.(gds|oas|spi|cdl)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]
        exclude: ^(.*\.json\.gz|.*\.min\.(js|css))$

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-tabs
        exclude: \.mk$|Makefile$|\.go$

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        args: [tests/unit/, --tb=short, -x]
        pass_filenames: false
        always_run: false
        stages: [manual]

      - id: security-check
        name: security-check
        entry: python
        language: system
        args: [-m, bandit, -r, holo_code_gen/, -f, json, -o, security-report.json]
        pass_filenames: false
        files: \.py$
        always_run: false
        stages: [manual]

      - id: docs-check
        name: docs-check
        entry: python
        language: system
        args: [-c, "import holo_code_gen; print('Imports successful')"]
        pass_filenames: false
        always_run: false
        stages: [manual]

      - id: circuit-validation
        name: circuit-validation
        description: Validate photonic circuit files
        entry: python
        language: system
        args: [-c, "
import sys
from pathlib import Path
for file in sys.argv[1:]:
    if file.endswith(('.gds', '.oas')):
        print(f'Binary file {file} - skipping validation')
    elif file.endswith('.spi'):
        with open(file) as f:
            content = f.read()
            if not content.strip().endswith('.END'):
                print(f'Warning: {file} missing .END directive')
        "]
        files: \.(gds|oas|spi|cdl)$
        stages: [manual]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false